### ISSUE TITLE
Typos in Troll Paper

### ISSUE THREAD

**Issue by ChrisEPhifer** [150PLD-Fall2019/Reading#1]
Here are some typos from the Troll paper. Only the second one _really_ matters, the first is obviously a mistype.

- Section 2, "The Basics of Troll": "When you roll several dice at the same **dice**..."
- Section 3, "Differences From Roll": Fourth bullet point conflates `< 3 x` with `3 > x`, where it should absolutely be `3 < x`.

**Comment by mpahrens** [comment]
Thank you for finding these. would you be able to add as an errata section to [https://github.com/150PLD-Fall2019/Reading/wiki/Class-01-Troll](https://github.com/150PLD-Fall2019/Reading/wiki/Class-01-Troll)?

**Comment by ChrisEPhifer** [comment]
Done!

**Comment by mpahrens** [comment]
Thanks!
