### ISSUE TITLE
9/16 Manager

### ISSUE THREAD

**Issue by jmusca** [150PLD-Fall2019/Reading#10]
Jeanne-Marie Musca

**Comment by mpahrens** [comment]
JM, let me know what you thought of time management in today's course and then assign the issue back to me.

**Comment by jmusca** [comment]
The time for different parts of the class was nicely distributed yesterday. We had a good amount of time to talk in a small group, and to discuss as a whole class.

Within our group, I didn't have to do much to manage the time, we essentially sped through the questions. In one sense, I think we may have gone to quickly over some questions. I think we adopted the style of getting a "good enough" answer to the question as fast as possible and moving on to the next, instead of discussing different dimensions of a particular question. 

This might be the desired approach. It did mean that we had time to look at all the questions. However, I think there can be something gained from dwelling on a question, even when you think you have the answer. This is something that managers could try to encourage, but I think that the method for doing so really varies depending on the set of questions and make up of the group.

On a separate note: when in class questions are about the content of a paper, it might be useful to give citations that locate the question in a context, and when answers are about what a paper said, it could be part of the exercise to give a rough citation of supporting text? Not sure if that would make sense to do, but just putting it out there.

**Comment by mpahrens** [comment]
Thanks for your feedback. The citation idea is particularly interesting, but I'm not sure how to support it right now. I definitely want us to start doing this tho, as it will be a skill necessary for technical reading and writing mastery.
