### ISSUE TITLE
9/16 Scribe

### ISSUE THREAD

**Issue by jmusca** [150PLD-Fall2019/Reading#11]
David Zabner

**Comment by mpahrens** [comment]
I don't have any commits from you for that wiki page. Are you good?

**Comment by nw0428** [comment]
I looked through the page and didn't have anything to add (i.e. All of the things my group discussed were already on the page).
I could make a small no-change commit but I don't think that would accomplish much.

**Comment by mpahrens** [comment]
Just wanted to confirm; Thank you!

**Comment by nw0428** [comment]
@mpahrens For clarity. What is the correct action to take in a situation where you feel there is nothing additional to scribe?

**Comment by mpahrens** [comment]
I do not have a set policy; but commenting on your role ticket that your manager has made is sufficient and easy (I hope)
