### ISSUE TITLE
Manager

### ISSUE THREAD

**Issue by natebragg** [150PLD-Fall2019/Reading#14]
Nate Bragg

**Comment by mpahrens** [comment]
Nate, let me know your thoughts on time management in today's course and then assign the issue back to me.

**Comment by natebragg** [comment]
It was mostly smooth.  My only comment would be to make sure we guarantee slightly more time to the 3-person discussions.  I tried to rush our group a little to make sure we got to every question (which we did), and it would have been nice to have another minute or so per question.

**Comment by mpahrens** [comment]
Thanks for your feedback. I agree and as we scope discussions, I will consider this since we also want to schedule time explicitly for answers to the prior nights homework (which ate up some of the 3-person group time today).
