### ISSUE TITLE
Caring about the users

### ISSUE THREAD

**Issue by uwaces** [150PLD-Fall2019/Reading#180]
# Libraries as Design
Today in class we talk a lot about how the users were overlooked in the development of Latte. I wanted to present a language that took a radically opposite approach. Elm is a functional compile to JavaScript language who's users are coming from JS, a dynamically typed language. I found the exchange in this [API Design Review](https://youtu.be/KSuCYUqY058?t=3544) done with Evan and a JS programmer.

> JS Developer: "...I think example-driven development helps here. 
> Elm Designer: "Um... oh yeah at this point we might have enough code to do some prototype... let's do that I guess..."
> JS Developer: "It would be nice to throw something up on the screen for people"
> Elm Designer: "You think we could just implement... what do you mean throw something on the screen?"
> JS Developer: "I mean we could have a simple beginner program and then import something from this (library) and then have our own input field and then see if we could get some kind of click behavior to just update our API ... (inaudible)... and then that way we could assess whether or not this API makes sense.
> Elm Designer: "Yeah, or we could write the code pretending that we implemented it."
> JS Developer: "This is true too. (Laughter) I feel like you are particularly better at envisioning the end goal. I feel like a lot of JS developers need the..."
> Elm Designer: "I mean... showing examples is a better way too... yeah, ok but I want to think a little more before we do that... I mean it doesn't feel like we're done.... to me"
> JS Developer: "Yeah considering our update function is a type annotation."
> Elm Designer: "No... no... no... but... I... One thing that people have been surprised by is you just implement it thats not the hard part. Nothing i..."
> JS Developer: "The design..."
> Elm Designer: Yeah exactly like this is the only thing that matters, like, to a user. Um.. and like obvoiusly we can just implement this... it's not out of the question. Um... but like are we actually like covering all the surface area here? What would we want to expose, like, so let's see..."

The discussion goes on to be quite productive and they realize parts of the way the library could be used they wouldn't have seen otherwise. This level of understanding and focus on design is the reason I study programming language design. Even if I never design a programming language I am a much better programmer for it.

# Focus on Error Messages
The first time Elm focused on this issue was in 2015 with the article [Compiler Errors for Humans](https://elm-lang.org/news/compiler-errors-for-humans) in the article Evan Czaplicki makes the claim that "folks who prefer dynamically-typed languages are generally of the opinion that working with compiler error messages sucks". This is a perspective I understand, but find it difficult to sympathize with, largely because I understand the trade-offs involved (namely trading compile-time issue with run-time problems). Elm's focus on error messages has made it have a competitive edge against may other languages trying to fill this space. This improvement has been a large multiyear engineering effort. A [github repo](https://github.com/elm/error-message-catalog) was opened to collect example programs that cause all possible error messages and the error messages have been a focus of [multiple](https://elm-lang.org/news/compilers-as-assistants) [releases](https://elm-lang.org/news/the-syntax-cliff). In [the most recent article](https://elm-lang.org/news/the-syntax-cliff), he talks about how the design of Elm's syntax is built so that the parser can give very nice error messages. For example, the definition syntax requires indentation so that when something is missing off a definition the parser knows which definition was missing something.

We could all do better by focousing on our user's needs and letting that motivate our language design.

**Comment by mpahrens** [comment]
Promoting this to a wiki article
