### ISSUE TITLE
Hakaru Paper - Broken Link

### ISSUE THREAD

**Issue by ChrisEPhifer** [150PLD-Fall2019/Reading#270]
The Hakaru paper link on the assignment page is broken. For reference, the paper is available here: https://www.researchgate.net/publication/303296396_Probabilistic_Inference_by_Program_Transformation_in_Hakaru_System_Description

**Comment by mpahrens** [comment]
The link works for me on my phone just now,  so I don't know what's up.
I'll check tomorrow on my computer

**Comment by ChrisEPhifer** [comment]
Interesting; this is what I get (with a clean browser cache etc):

![Screen Shot 2019-11-16 at 12 36 57 AM](https://user-images.githubusercontent.com/22036533/68988691-501c9600-0809-11ea-8b34-0752eba9ba2c.png)

**Comment by mpahrens** [comment]
I got the link from the bottom of their github.io page.  See if you can
find it and if it is the same for you,  but that's really weird.  Maybe try
http instead of https?

**Comment by ChrisEPhifer** [comment]
I tried that link as well, and had no luck with `http`. No big deal; the link I posted in the original issue comment works just fine :)

**Comment by mpahrens** [comment]
In any case, I made a local copy and updated the link, as well as pushed a copy to the reading repo. So, now all the bases should be covered.
