### ISSUE TITLE
Merge elif's TH class notes with the main wiki for TH

### ISSUE THREAD

**Issue by mpahrens** [150PLD-Fall2019/Reading#29]
There is a class discussion file for TH that is separate from the TH file linked from the class agenda.
Someone can earn extra credit by merging them.

**Comment by jmusca** [comment]
I'm going to do it, by basically copy pasting. I'll leave the issue open, in case there's something more that needs doing.

**Comment by jmusca** [comment]
Done: https://github.com/150PLD-Fall2019/Reading/wiki/Class-03-Template-Haskell

**Comment by mpahrens** [comment]
Looks good!
