### ISSUE TITLE
Special Topic - Harrison Kaiser - Elm Language - A look at a DSL's evolution over time

### ISSUE THREAD

**Issue by uwaces** [150PLD-Fall2019/Reading#295]
Elm is a programming language which compiles to JavaScript and is designed specifically for building web applications. Of interest to us is the ability of the language to change over time. Both in the syntax and evaluation model Elm has changed in response to real-world use as opposed to cool new ideas. The results of this kind of design have a deep downstream effect on the software ecosystem.

**Comment by uwaces** [comment]
Posted on reading wiki

**Comment by mpahrens** [comment]
Thanks again for the suggestion!
