### ISSUE TITLE
Eval Criteria Criticisms

### ISSUE THREAD

**Issue by elif01** [150PLD-Fall2019/Reading#296]
Software Ecosystem:
---------------------
Too heavily focused on Haskell usage. If it’s good work that should suffice. 
Strong accept criteria: Not everything that’s created is meant to be integrated with other things. 
Perhaps better: “Is the software ecosystem appropriate for the end-user’s needs?”
“I should be able to clone it, compile it, be able to understand it” 

Software Engineering:
----------------------
You dont have to have an API 
**What is** an API (people don’t seem to agree on a definition!)
-- “All the ways the user can interact with your language” 
-- We are evaluating the code THEY WROTE — how are we gonna do that? is API the correct term here?
Why do you have to justify library usage? 
More of interest: “Did they use the features of the host language to their advantage?”

Abstract Syntax and Internal Representations
--------------------------------------------
Spelling out “important things” — we want to put in a point of reference 
—> Alternative : instead of saying “missing important things”, focusing on their justifications of what they have included and what they havent included. 

Related Work 
-------------
Using “at length” perhaps focuses on quantity over quality    — under what context what is sufficient?

Clarity
------- 
Suggestion: terms are well defined *for the target audience*

Documentation and Usability 
-----------------------------

Codegen / Metaprogramming etc:
----------------------------------
What if your language wont be needing these capabilities?
Matt poses a controversial question in response:  “If it doesn’t do anything at compile time is it a language or a runtime library?”

Evaluation 
-----------
"Most" and "all" rather than 3

**Comment by jjkv** [comment]
edited per these notes
