### ISSUE TITLE
What is mappend for Tree?

### ISSUE THREAD

**Issue by uwaces** [150PLD-Fall2019/Reading#30]
I was able to solve the applicative homework in the Tree case without understanding what mappend is defined to be for Tree. 

Can we talk about what mappend is for tree and what the intuition is?

**Comment by mpahrens** [comment]
Yes, this was asked about by other students so we will go over it in class.
In case you want to return to the topic after my explanation, I also recorded a small video explaining it.

https://youtu.be/VHOC4QAgUXg

Also, to avoid confusion. `mappend` is Monoid append, which would define how to take two trees of the same value and merge them. What was being asked in the homework was applicative ap or `<*>` which defines how to take a tree of functions and apply each function to a tree of values.

So for the homework, you did not need to use mappend, but if you meant you did not understand `<*>` I hope I can illuminate that for you.

For everyone who comes across this issue, the learning objective I intended from this exercise was not for you to memorize the specific applicative behavior of a Tree, but to encounter the way designers instantiate these common design patterns for their particular data structure. When I was learning these things, I initially expected all instances of Applicatives (or functors, or monads) to behave the "same" way. And that is not the reality. But as per the disclaimer I gave in class, not everyone learns the same way and so I apologize if you found these exercises more detrimental to your learning than engaging.
