### ISSUE TITLE
Grading Timeline

### ISSUE THREAD

**Issue by 3geek14** [150PLD-Fall2019/Reading#9]
I'm getting curious if my submissions have been satisfying the learning objectives I've been claiming they do.  Is there an expected average turnaround time between submitting an assignment and getting an update to our `grades.csv` file?  Will commits that update `grades.csv` include comments saying which assignments have contributed to which boxes (and which assignments, if any, have been graded but failed to contribute to any boxes)?

**Comment by mpahrens** [comment]
I hope my announcement in class answered your issue; however, for posterity, I hope to have assignments turned around within a week of being turned in. Feel free to close if you have no follow up questions
